### ISSUE TITLE
Paste produces invalid values

### ISSUE THREAD

**Issue by pekkavaa** [edoreshef/ground-control#5]
When copying & pasting values are parsed incorrectly if they have nonzero digits after the decimal point, and the locale uses comma as a decimal separator.

Steps to reproduce:
1. Set system locale to one that uses commas as separator e.g. Finnish
2. Enter value `1.1` to a track
3. Copy and paste the value to another track.

The resulting value is `11`, not `1.1`. 
The comma decimal separator also shows up in the GUI as can be seen also in the attached screenshot.

![2016-05-21 18_04_42-clipboard](https://cloud.githubusercontent.com/assets/934568/15449170/c802169e-1f7e-11e6-9470-0db1caacbbc2.png)

**Comment by edoreshef** [comment]
Fixed @ 96574a8a3f22a0dcf994518c19ab243f229a6112
locale is overwritten by "InvariantCulture"
