### ISSUE TITLE
Readme is missing key shortcut for "insert current value"

### ISSUE THREAD

**Issue by pekkavaa** [edoreshef/ground-control#6]
Pressing Shift+Enter creates a new item using the current interpolated track value but this isn't said in the readme.

**Comment by edoreshef** [comment]
Actually, adding values by current track value is done by "Enter" (without the Shift).
This is mentioned in the readme - Though description should probably be improved...

**Comment by pekkavaa** [comment]
Ah alright :) It's very handy.
