### ISSUE TITLE
Statusbar is not updated when changing interpolation mode

### ISSUE THREAD

**Issue by pekkavaa** [edoreshef/ground-control#7]
A minor cosmetic issue: when pressing `i` the current interpolation mode index isn't updated on the status bar on the lower right hand corner. This only matters in the case of the rightmost track where the color coded interpolation mode ribbon is obscured by the waveform view (a little bug also :).

**Comment by edoreshef** [comment]
Status bar not updated bug solved @ 96574a8a3f22a0dcf994518c19ab243f229a6112
Interpolation bar not visible when scrolling bug solved @ 1dbaf4d61c67a16617006141e1405a5cfd634b36
